services:
  server:
    container_name: prom_ws_server
    build:
      context: ./
      dockerfile: ./server.dockerfile
    environment:
      APP_PORT: 80
    ports:
      - 23054:80
    expose:
      - 80
  poller:
    container_name: prom_ws_poller
    build:
      context: ./
      dockerfile: ./poller.dockerfile
    environment:
      SERVER_URL: http://prom_ws_server:80
  prometheus:
    container_name: prom_ws_collector
    image: ubuntu/prometheus:2.46-22.04
    ports:
      - 23055:9090 # expression browser
    # tsdb volume
  # busybox:
  #   image: busybox:1.35
  #   command: ['tail', '-f', '/dev/null']
