services:
  server:
    build:
      context: ./
      dockerfile: ./server.dockerfile
    environment:
      APP_PORT: 80
    ports:
      - 23054:80
    expose:
      - 80
  poller:
    build:
      context: ./
      dockerfile: ./poller.dockerfile
    environment:
      SERVER_URL: http://server:80
  prometheus:
    image: ubuntu/prometheus:2.46-22.04
    ports:
      - 23055:9090 # expression browser
  # busybox:
  #   image: busybox:1.35
  #   command: ['tail', '-f', '/dev/null']
