services:
  server:
    container_name: prom_ws_server
    build:
      context: ./
      dockerfile: ./server.dockerfile
    environment:
      APP_PORT: 80
    ports:
      - 23054:80
    expose:
      - 80
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s
  poller:
    container_name: prom_ws_poller
    build:
      context: ./
      dockerfile: ./poller.dockerfile
    environment:
      SERVER_URL: http://prom_ws_server:80
    depends_on:
      server:
        condition: service_healthy
  prometheus:
    container_name: prom_ws_collector
    image: ubuntu/prometheus:2.46-22.04
    # TODO: expose the port within the Docker network
    # expose:
    #   - 9090
    ports:
      - 23055:9090 # expression browser
    volumes:
      - ./config:/etc/prometheus:ro
      - ./prom_data:/prometheus:rw
  alertmanager:
    container_name: prom_ws_alertmanager
    image: prom/alertmanager:v0.26.0
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 29093:9093 # web ui is also available at this port
    user: root
    volumes:
      - ./alertmanager_config:/config:ro
      - ./alertmanager_data:/alertmanager:rw
    command:
      - '--config.file=/config/alertmanager.yml'
      - '--log.level=debug'
  # busybox:
  #   image: busybox:1.35
  #   command: ['tail', '-f', '/dev/null']
